server:
  port: 8083

spring:
  application:
    name: notification-service
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${LOCALE_DB_URL_NOTIFICATION}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  datasource:
    url: ${LOCALE_DB_URL_NOTIFICATION}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: core.core.dto.TransactionKafkaEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION}
      cookie-name: jwt_token
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}