eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8082
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${LOCALE_DB_URL_TRAN}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  datasource:
    url: ${LOCALE_DB_URL_TRAN}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  data:
    redis:
      port: 6379
      host: localhost
  cache:
    type: redis
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 10000
        linger.ms: 0
        request.timeout.ms: 5000
  application:
    name: transaction-service

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION}
      cookie-name: jwt_token

claude:
  api:
    key: ${CLAUDE_API_KEY}